/**
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 * https://github.com/CILEA/dspace-cris/wiki/License
 */
package org.dspace.app.cris.discovery;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import org.apache.commons.lang3.StringUtils;
import org.apache.solr.common.SolrInputDocument;
import org.dspace.app.cris.model.ACrisObject;
import org.dspace.app.cris.model.CrisConstants;
import org.dspace.app.cris.model.ResearcherPage;
import org.dspace.app.cris.model.jdyna.ACrisNestedObject;
import org.dspace.content.DCPersonName;
import org.dspace.core.ConfigurationManager;
import org.dspace.discovery.configuration.DiscoverySearchFilter;
import org.paukov.combinatorics3.Generator;

import it.cilea.osd.jdyna.model.ANestedPropertiesDefinition;
import it.cilea.osd.jdyna.model.ANestedProperty;
import it.cilea.osd.jdyna.model.ATypeNestedObject;
import it.cilea.osd.jdyna.model.PropertiesDefinition;
import it.cilea.osd.jdyna.model.Property;

/**
 * This index plugin add to the rp solr document all the abbrevations form that
 * can be generated by all the known rp names.
 * 
 * For example the input Pascarelli, Luigi Andrea produces
 * Pascarelli, Luigi A.
 * Pascarelli, L. Andrea
 * Pascarelli, Luigi
 * Pascarelli, Andrea
 * Pascarelli, L. A.
 * Pascarelli, A.
 * Pascarelli, L.
 * Pascarelli, A. L.
 * Pascarelli, AL
 * Pascarelli, LA
 * 
 * @author Andrea Bollini (andrea.bollini at 4science.it)
 *
 */
public class CRISPersonNamesGeneratorSolrIndexPlugin implements CrisServiceIndexPlugin{

	@Override
	public <P extends Property<TP>, TP extends PropertiesDefinition, NP extends ANestedProperty<NTP>, NTP extends ANestedPropertiesDefinition, ACNO extends ACrisNestedObject<NP, NTP, P, TP>, ATNO extends ATypeNestedObject<NTP>> void additionalIndex(
			ACrisObject<P, TP, NP, NTP, ACNO, ATNO> crisObject,
			SolrInputDocument document, Map<String, List<DiscoverySearchFilter>> searchFilters) {
		if (crisObject instanceof ResearcherPage){
			ResearcherPage rp = (ResearcherPage) crisObject;
			Set<String> generatedPubAbbrevations = new HashSet<String>();
			for (String s : rp.getAllNames()) {
				generatedPubAbbrevations.addAll(generateAbbreviations(s));
			}
			Set<String> generatedPrivAbbrevations = new HashSet<String>();
			for (String s : rp.getAllPrivateNames()) {
				generatedPrivAbbrevations.addAll(generateAbbreviations(s));
			}
			if (generatedPubAbbrevations.size() > 0) {
				document.addField("crisrpnamesabbreviations",generatedPubAbbrevations);
			}
			if (generatedPrivAbbrevations.size() > 0) {
				document.addField("crisrpnamesabbreviations_private",generatedPrivAbbrevations);
				String searchablePrivateFieldsCfg = ConfigurationManager.getProperty(CrisConstants.CFG_MODULE, "system.search.private.fields");
	        	if (searchablePrivateFieldsCfg != null) {
	        		List<String> searchablePrivateFields = Arrays.asList(searchablePrivateFieldsCfg.split("\\s*,\\s*"));
	        		if (searchablePrivateFields.contains("crisrpnamesabbreviations")) {
	        			document.addField("crisrpnamesabbreviations_restrictedvisibility", generatedPrivAbbrevations);	
	        		}
	        	}
			}
		}
	}
	
	private static List<String> generateAbbreviations(String s) {
		List<String> results = new ArrayList<String>();
		DCPersonName name = new DCPersonName(s);
		if (StringUtils.isNotBlank(name.getFirstNames())) {
			String[] fnames = name.getFirstNames().split("[\\s-]");
			// we assume that fnames as unique values as it makes sense
			Set<String> firstNames = Arrays.stream(fnames).filter(r -> StringUtils.isNotBlank(r)).collect(Collectors.toSet());
			for (int i = 1; i <= 3 && i <= fnames.length; i++) {
				List<List<String>> combinations =  Generator.combination(firstNames).simple(i).stream().collect(Collectors.toList());
				for (List<String> c : combinations) {
					List<List<String>> permutations = Generator.permutation(c).simple().stream().collect(Collectors.toList());
					for (List<String> p : permutations) {
						results.add(name.getLastName() + ", " + p.stream().filter(r -> StringUtils.isNotBlank(r)).collect(Collectors.joining(" ")));
						results.add(name.getLastName() + ", " + p.stream().map(r -> r.substring(0, 1)).collect(Collectors.joining(". ")) + ".");
						results.add(name.getLastName() + ", " + p.stream().map(r -> r.substring(0, 1)).collect(Collectors.joining("")));
					}
				}
			}
		}
		
		return results;
	}

	@Override
	public <P extends Property<TP>, TP extends PropertiesDefinition, NP extends ANestedProperty<NTP>, NTP extends ANestedPropertiesDefinition, ACNO extends ACrisNestedObject<NP, NTP, P, TP>, ATNO extends ATypeNestedObject<NTP>> void additionalIndex(
			ACNO dso, SolrInputDocument sorlDoc, Map<String, List<DiscoverySearchFilter>> searchFilters) {
	}

	public static void main(String[] args) {
		String[] inputs = new String[] {"Pascarelli, Luigi Andrea", "Bollini, Andrea", "De Florio, Ramon-Alberto", "Invalid name"};
		for (String s : inputs) {
			System.out.println(s);
			for (String o : generateAbbreviations(s)) {
				System.out.println(" ---> " + o);	
			}
		}
	}
}
