#---------------------------------------------------------------#
#--------------SCHEMA ORG FIELD CONFIGURATION--------------#
#---------------------------------------------------------------#
schemaorg.dataset.name = dc.title
schemaorg.dataset.author = firstauthorschemaorg
schemaorg.dataset.description = dc.description.abstract
schemaorg.dataset.url = $handle
schemaorg.dataset.sameAs =
schemaorg.dataset.identifier = dc.identifier.doi, tuhh.publisher.doi, dc.identifier.urn, dc.identifier.scopus, dc.identifier.pmid, $simple-handle, dc.identifier.isi
schemaorg.dataset.keywords = dc.subject
schemaorg.dataset.license = dc.rights.uri
schemaorg.dataset.hasPart =
schemaorg.dataset.creator = creatorschemaorg
schemaorg.dataset.funder = funderchemaorg
schemaorg.dataset.includedInDataCatalog =
schemaorg.dataset.distribution =
schemaorg.dataset.temporalCoverage = dc.date.issued
schemaorg.dataset.spatialCoverage =
